type FACULTY {
  FACULTY: String!
  FACULTY_NAME: String!
}

type TEACHER {
  TEACHER: String!
  TEACHER_NAME: String!
  PULPIT: String!
}

type PULPIT {
  PULPIT: String!
  PULPIT_NAME: String!
  FACULTY: String!
}

type SUBJECT {
  SUBJECT: String!
  SUBJECT_NAME: String!
  PULPIT: String!
}

type TeachersByFaculty {
  FACULTY: String!
  TEACHERS: [TEACHER]
}

type SubjectsByFaculties {
  PULPIT: String!
  PULPIT_NAME: String!
  FACULTY: String!
  SUBJECTS: [SUBJECT]
}

type Query {
  getFaculties(FACULTY: String): [FACULTY]
  getPulpits(PULPIT: String): [PULPIT]
  getTeachers(TEACHER: String): [TEACHER]
  getSubjects(SUBJECT: String): [SUBJECT]
  getTeachersByFaculty(FACULTY: String!): [TeachersByFaculty]
  getSubjectsByFaculties(FACULTY: String!): [SubjectsByFaculties]
}

type Mutation {
  setFaculty(FACULTY: String!, FACULTY_NAME: String!): FACULTY
  setPulpit(PULPIT: String!, PULPIT_NAME: String!, FACULTY: String!): PULPIT
  setTeacher(TEACHER: String!, TEACHER_NAME: String!, PULPIT: String!): TEACHER
  setSubject(SUBJECT: String!, SUBJECT_NAME: String!, PULPIT: String!): SUBJECT

  delFaculty(FACULTY: String!): Boolean
  delPulpit(PULPIT: String!): Boolean
  delTeacher(TEACHER: String!): Boolean
  delSubject(SUBJECT: String!): Boolean
}
